version: '3'
services:
  nginx:
    container_name: home-nginx
    restart: always
    image: nginx:1.18.0
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/usr/local/server.crt
      - ./nginx/server.key:/usr/local/server.key

  db:
    container_name: home-db
    restart: always
    image: mysql:8.0.13
    ports:
      - 7706:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    container_name: springboot
    restart: always
    image: openjdk:8
    depends_on:
      - db
    volumes:
      - ./web/api.jar:/usr/api.jar
    command: bash -c "java -jar /usr/api.jar"

