version: '3'
services:
  certbot:
    container_name: home-certbot
    restart: always
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 720h & wait $${!}; done;'"

  nginx:
    container_name: home-nginx
    restart: always
    image: nginx:1.18.0
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    links:
      - web:web
    volumes:
      - ./html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 720h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  db:
    container_name: home-db
    restart: always
    image: mysql:8.0.13
    ports:
      - 7706:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    container_name: springboot
    restart: always
    image: gradle:6.7.1-jdk8
    depends_on:
      - db
    volumes:
      - ./api:/home/gradle/project
    command: bash -c "cd /home/gradle/project && gradle bootRun"

