version: '3'
services:
  nginx:
    container_name: home-nginx
    restart: always
    image: nginx:1.18.0
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    container_name: home-db
    restart: always
    image: mysql:8.0.13
    ports:
      - 7706:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: bash -c "mysql start"

  web:
    container_name: springboot
    restart: always
    image: openjdk:8
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./web/api.jar:/usr/api.jar
    command: bash -c "java -jar /usr/api.jar"

